## Nexys Video (XC7A200T-1SBG484C) constraints for plena_a7_top
## Only top-level board I/O is constrained here; DDR3 pin constraints are generated by
## the MIG IP. Ports must match plena_a7_top: sys_clk, sys_rst_n, led[6:0].

## Clock signal (100 MHz)
set_property -dict { PACKAGE_PIN R4 IOSTANDARD LVCMOS33 } [get_ports { sys_clk }]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { sys_clk }]

## Reset (active-low CPU reset button)
set_property -dict { PACKAGE_PIN G4 IOSTANDARD LVCMOS15 } [get_ports { sys_rst_n }]

## LEDs
set_property -dict { PACKAGE_PIN T14 IOSTANDARD LVCMOS25 } [get_ports { led[0] }]
set_property -dict { PACKAGE_PIN T15 IOSTANDARD LVCMOS25 } [get_ports { led[1] }]
set_property -dict { PACKAGE_PIN T16 IOSTANDARD LVCMOS25 } [get_ports { led[2] }]
set_property -dict { PACKAGE_PIN U16 IOSTANDARD LVCMOS25 } [get_ports { led[3] }]
set_property -dict { PACKAGE_PIN V15 IOSTANDARD LVCMOS25 } [get_ports { led[4] }]
set_property -dict { PACKAGE_PIN U17 IOSTANDARD LVCMOS25 } [get_ports { led[5] }]
set_property -dict { PACKAGE_PIN W17 IOSTANDARD LVCMOS25 } [get_ports { led[6] }]

## DDR3 constraints are generated by the MIG IP — do not manually constrain here.

## Clock-domain crossing: the core runs on the MIG ui_addn_clk_0 (25 MHz), the MIG s_axi on
## ui_clk (100 MHz). The axi_clock_converter IP constrains its own async AXI FIFOs. Here we only
## false-path the two single-bit synchronizers into the core domain (reset + calib-done), which
## are 2-FF ASYNC_REG synchronizers by construction.
set_false_path -to [get_cells -hier -filter {NAME =~ *core_rst_sync_ff_reg[0]*}]
set_false_path -to [get_cells -hier -filter {NAME =~ *calib_sync_ff_reg[0]*}]

## Configuration
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
