`timescale 1ns / 1ps

`include "global_define.vh"
`include "precision.svh"
`include "configuration.svh"
`include "operation.svh"
`include "tl_pkg.svh"
`include "tl_util.svh"
`include "prim_util_pkg.svh"

/*
Module      : PLENA Nexys A7 / Nexys Video board top (plena_a7_top)
Description : Connects the PLENA core to on-board DDR3 through the tl_to_axi4 burst
              bridge and a Xilinx MIG 7-series controller. Board-level replacement for
              the simulation-only plena_artix7_top / generic plena_v80_top.

              The core fetches instructions over its TileLink instr_mem_tl host port and
              issues HBM data traffic on four TileLink host ports (matrix/vector ×
              element/scale). Those four data channels are arbitrated (priority
              m_element > m_scale > v_element > v_scale) into a single tl_to_axi4 bridge,
              whose AXI4 master drives the MIG DDR3 AXI slave. Instructions are served
              from a small on-chip ROM responder.
*/

module plena_a7_top import configuration_pkg::*; import instruction_pkg::*; (
    // Board clock / reset
    input  wire        sys_clk,        // 100 MHz single-ended board clock
    input  wire        sys_rst_n,      // active-low reset

    // DDR3 physical interface (constraints generated by the MIG IP)
    output wire [14:0] ddr3_addr,
    output wire [2:0]  ddr3_ba,
    output wire        ddr3_cas_n,
    output wire        ddr3_ck_n,
    output wire        ddr3_ck_p,
    output wire        ddr3_cke,
    output wire        ddr3_ras_n,
    output wire        ddr3_reset_n,
    output wire        ddr3_we_n,
    inout  wire [15:0] ddr3_dq,
    inout  wire [1:0]  ddr3_dqs_n,
    inout  wire [1:0]  ddr3_dqs_p,
    output wire [1:0]  ddr3_dm,
    output wire        ddr3_odt,

    // Status LEDs
    output logic [6:0] led
);

    // ---- Bridge / AXI geometry (must match mig_nexys_video.prj AXIParameters) ----
    localparam int BRIDGE_DATA_W = HBM_WIDTH;            // = HBM_ELE_WIDTH (power of two)
    localparam int BRIDGE_MASK_W = BRIDGE_DATA_W / 8;
    localparam int AXI_DATA_W    = 128;                  // C0_S_AXI_DATA_WIDTH
    localparam int AXI_ADDR_W    = 29;                   // C0_S_AXI_ADDR_WIDTH (512 MB DDR3)
    localparam int AXI_ID_W      = 4;                    // C0_S_AXI_ID_WIDTH
    localparam int AXI_STRB_W    = AXI_DATA_W / 8;
    // Single full-width transfer per request: TL size = clog2(bytes per bridge beat).
    localparam logic [`TL_SIZE_WIDTH-1:0] BRIDGE_TL_SIZE = `TL_SIZE_WIDTH'($clog2(BRIDGE_DATA_W/8));

    wire ui_clk, ui_clk_sync_rst;
    wire ui_addn_clk_0;             // MIG MMCM extra output = 50 MHz core clock (timing closure)
    wire init_calib_complete;
    wire sys_clk_bufg;
    // The core/TileLink domain runs at 50 MHz so the MLEN=16 systolic datapath closes timing
    // (it tops out ~31 MHz); only the MIG PHY + s_axi stay at 100 MHz ui_clk, crossed by one
    // axi_clock_converter below.
    wire plena_clk = ui_addn_clk_0;
    logic system_break;     // internal status, surfaced on led[0]

    BUFG bufg_ref (.I(sys_clk), .O(sys_clk_bufg));

    // Reset synchronizer into the core_clk (50 MHz) domain: async-assert from the MIG's
    // ui_clk_sync_rst (which already folds in MMCM lock + calibration), sync-deassert on plena_clk.
    (* ASYNC_REG = "TRUE" *) logic [1:0] core_rst_sync_ff;
    always_ff @(posedge plena_clk or posedge ui_clk_sync_rst) begin
        if (ui_clk_sync_rst) core_rst_sync_ff <= 2'b11;
        else                 core_rst_sync_ff <= {core_rst_sync_ff[0], 1'b0};
    end
    wire core_rst = core_rst_sync_ff[1];

    // init_calib_complete is a ui_clk-domain level from the MIG; 2-FF sync it before the
    // core-domain STATUS register samples it.
    (* ASYNC_REG = "TRUE" *) logic [1:0] calib_sync_ff;
    always_ff @(posedge plena_clk) calib_sync_ff <= {calib_sync_ff[0], init_calib_complete};
    wire init_calib_complete_sync = calib_sync_ff[1];

    // ---- Soft reset: an AXI-lite SOFT_RST write holds the core in reset for 16 cycles ----
    logic        soft_rst_pulse;            // 1-cycle pulse from the AXI-lite block (below)
    logic [4:0]  soft_rst_cnt;
    always_ff @(posedge plena_clk) begin
        if (core_rst)               soft_rst_cnt <= '0;
        else if (soft_rst_pulse)    soft_rst_cnt <= 5'd16;
        else if (soft_rst_cnt != 0) soft_rst_cnt <= soft_rst_cnt - 1'b1;
    end
    wire soft_rst  = (soft_rst_cnt != 0);
    // Hold the core in reset until the first SOFT_RST launch so it cannot execute an unloaded
    // (garbage) IMEM -- and issue stray HBM/DDR3 traffic -- before the host loads the program.
    logic core_launched;
    always_ff @(posedge plena_clk) begin
        if (core_rst)            core_launched <= 1'b0;
        else if (soft_rst_pulse) core_launched <= 1'b1;
    end
    wire plena_rst = core_rst | soft_rst | ~core_launched;   // core reset (held until first SOFT_RST)
    // The HBM datapath (bridge/regslices/FIFOs/loader) resets only on the (synchronized) MIG reset,
    // so it stays LIVE while the core is held in reset (core_launched=0) -- the JTAG DDR3 loader
    // needs the bridge then.
    wire dp_rst = core_rst;

    // system_break is a combinational 1-cycle pulse (core keeps fetching NOPs past C_BREAK); latch
    // it sticky (cleared per launch) so a host polling STATUS over slow JTAG cannot miss the pulse.
    logic system_break_latched;
    always_ff @(posedge plena_clk) begin
        if (plena_rst)         system_break_latched <= 1'b0;   // plena_rst already folds in core_rst
        else if (system_break) system_break_latched <= 1'b1;
    end

    // ---- VSRAM debug-readback control (driven by the AXI-lite block) ----
    logic                          dbg_vsram_en;
    logic [ON_CHIP_ADDR_WIDTH-1:0] dbg_row;
    wire  [VECTOR_SRAM_WIDTH-1:0]  dbg_vsram_data;

    // =========================================================
    // PLENA core — TileLink host ports
    // =========================================================
    `TL_DECLARE(INSTRUCTION_LENGTH, HBM_ADDR_WIDTH, SourceWidth, SinkWidth, instr_mem);
    `TL_DECLARE(HBM_ELE_WIDTH,   HBM_ADDR_WIDTH, SourceWidth, SinkWidth, m_element);
    `TL_DECLARE(HBM_SCALE_WIDTH, HBM_ADDR_WIDTH, SourceWidth, SinkWidth, m_scale);
    `TL_DECLARE(HBM_ELE_WIDTH,   HBM_ADDR_WIDTH, SourceWidth, SinkWidth, v_element);
    `TL_DECLARE(HBM_SCALE_WIDTH, HBM_ADDR_WIDTH, SourceWidth, SinkWidth, v_scale);

    plena plena_core (
        .clk(plena_clk),
        .rst(plena_rst),
        .system_break(system_break),
        `TL_CONNECT_HOST_PORT(instr_mem_tl,  instr_mem),
        `TL_CONNECT_HOST_PORT(m_out_element, m_element),
        `TL_CONNECT_HOST_PORT(m_out_scale,   m_scale),
        `TL_CONNECT_HOST_PORT(v_out_element, v_element),
        `TL_CONNECT_HOST_PORT(v_out_scale,   v_scale),
        .debug_vsram_en   (dbg_vsram_en),
        .debug_row        (dbg_row),
        .debug_vsram_data (dbg_vsram_data)
    );

    // =========================================================
    // Instruction memory: dual-port BRAM, host-loaded over AXI-lite, read by the core's
    // instr_mem_tl TileLink port via tl_adapter_bram (mirrors blou/v80 plena_v80_top).
    // =========================================================
    localparam int IMEM_DEPTH  = 512;
    localparam int IMEM_ADDR_W = $clog2(IMEM_DEPTH);

    logic [31:0]            imem [0:IMEM_DEPTH-1];

    // tl_adapter_bram BRAM port (TileLink read side)
    logic                   imem_bram_en, imem_bram_we;
    logic [IMEM_ADDR_W-1:0] imem_bram_addr;
    logic [3:0]             imem_bram_wmask;
    logic [31:0]            imem_bram_wdata, imem_bram_rdata;

    // AXI-lite program-load port
    logic                   imem_we_a;
    logic [IMEM_ADDR_W-1:0] imem_addr_a;
    logic [31:0]            imem_wdata_a;

    // Single always_ff models the true dual-port RAM (no multi-driver on imem).
    always_ff @(posedge plena_clk) begin
        if (imem_we_a)
            imem[imem_addr_a] <= imem_wdata_a;                   // port A: AXI-lite write
        if (imem_bram_en) begin                                  // port B: TileLink read
            if (imem_bram_we)
                for (int i = 0; i < 4; i++)
                    if (imem_bram_wmask[i])
                        imem[imem_bram_addr][8*i +: 8] <= imem_bram_wdata[8*i +: 8];
            imem_bram_rdata <= imem[imem_bram_addr];
        end
    end

    tl_adapter_bram #(
        .AddrWidth    (HBM_ADDR_WIDTH),
        .DataWidth    (INSTRUCTION_LENGTH),
        .SourceWidth  (SourceWidth),
        .BramAddrWidth(IMEM_ADDR_W)
    ) u_imem_adapter (
        .clk_i        (plena_clk),
        .rst_ni       (~core_rst),    // survives core soft-reset; IMEM persists
        `TL_CONNECT_DEVICE_PORT(host, instr_mem),
        .bram_en_o    (imem_bram_en),
        .bram_we_o    (imem_bram_we),
        .bram_addr_o  (imem_bram_addr),
        .bram_wmask_o (imem_bram_wmask),
        .bram_wdata_o (imem_bram_wdata),
        .bram_rdata_i (imem_bram_rdata)
    );

    // =========================================================
    // AXI-lite slave (32-bit) — program load, status, VSRAM readback, soft reset.
    // Driven by an on-chip JTAG-to-AXI master (no extra board pins). Word addr = addr[7:2]:
    //   0x00 W IMEM_DATA   push instruction word, wptr++      0x10 RW IMEM_WPTR
    //   0x04 R STATUS {init_calib,system_break}               0x14 W SOFT_RST / R FREE_RUN
    //   0x08 W DEBUG_CTRL  bit0 -> debug_vsram_en             0x18 R RST_CNT
    //   0x0C W DEBUG_ADDR  -> debug_row                       0x40.. R DEBUG_D0..D{N-1}
    // =========================================================
    localparam int DBG_WORDS = (VECTOR_SRAM_WIDTH + 31) / 32;
    logic [DBG_WORDS*32-1:0] dbg_cap;
    always_ff @(posedge plena_clk)
        dbg_cap <= {{(DBG_WORDS*32-VECTOR_SRAM_WIDTH){1'b0}}, dbg_vsram_data};

    logic [IMEM_ADDR_W-1:0] imem_wptr;
    logic [31:0]            free_run, rst_cnt;
    always_ff @(posedge plena_clk) begin
        free_run <= free_run + 1'b1;                     // free-running (never reset)
        if (core_rst)        rst_cnt <= '0;
        else if (plena_rst)  rst_cnt <= rst_cnt + 1'b1;  // cycles the core was held in reset
    end

    // ---- JTAG->DDR3 loader: host streams 128-bit beats into DDR3 over the same AXI-lite path
    // (DDR3_ADDR/W0..W3/GO), gated by LOAD_MODE which hands the tl_to_axi4 bridge to the loader
    // while the core is held in reset. DDR3_RD reads a beat back for verification. ----
    localparam int LDR_BEATB = BRIDGE_DATA_W / 8;   // bytes per beat
    // Host beat register is a fixed 4x32-bit (W0..W3/R0..R3) view; the low BRIDGE_DATA_W bits
    // are what actually cross to/from the bridge (BRIDGE_DATA_W = 128 at MLEN=16, 64 at MLEN=8).
    localparam int LDR_HOST_W  = (BRIDGE_DATA_W > 128) ? BRIDGE_DATA_W : 128;
    logic [AXI_ADDR_W-1:0]     ddr3_addr_q;
    logic [LDR_HOST_W-1:0]     ddr3_wbeat_q;
    logic [LDR_HOST_W-1:0]     ddr3_rbeat_q;
    logic                      ddr3_go_pulse, ddr3_rd_pulse, load_mode;
    logic                      loader_busy, loader_done;

    // AXI-lite master <-> slave wires (from jtag_axi)
    wire [31:0] la_awaddr;  wire la_awvalid, la_awready;
    wire [31:0] la_wdata;   wire [3:0] la_wstrb; wire la_wvalid, la_wready;
    wire [1:0]  la_bresp;   wire la_bvalid, la_bready;
    wire [31:0] la_araddr;  wire la_arvalid, la_arready;
    wire [31:0] la_rdata;   wire [1:0] la_rresp; wire la_rvalid, la_rready;

    // ---- Write channel (accept AW+W together; single outstanding) ----
    logic        bvalid_r;
    wire         wr_fire = la_awvalid & la_wvalid & ~bvalid_r;
    wire  [5:0]  wr_w    = la_awaddr[7:2];
    assign la_awready = wr_fire;
    assign la_wready  = wr_fire;
    assign la_bvalid  = bvalid_r;
    assign la_bresp   = 2'b00;
    assign imem_we_a    = wr_fire & (wr_w == 6'h00);     // IMEM_DATA
    assign imem_addr_a  = imem_wptr;
    assign imem_wdata_a = la_wdata;

    always_ff @(posedge plena_clk) begin
        if (core_rst) begin
            bvalid_r <= 1'b0; imem_wptr <= '0;
            dbg_vsram_en <= 1'b0; dbg_row <= '0; soft_rst_pulse <= 1'b0;
            ddr3_addr_q <= '0; ddr3_wbeat_q <= '0; load_mode <= 1'b0;
            ddr3_go_pulse <= 1'b0; ddr3_rd_pulse <= 1'b0;
        end else begin
            soft_rst_pulse <= 1'b0; ddr3_go_pulse <= 1'b0; ddr3_rd_pulse <= 1'b0;
            if (ddr3_go_pulse) ddr3_addr_q <= ddr3_addr_q + LDR_BEATB;  // auto-inc after each write beat
            if (wr_fire)        bvalid_r <= 1'b1;
            else if (la_bready) bvalid_r <= 1'b0;
            if (wr_fire) begin
                unique case (wr_w)
                    6'h00: imem_wptr <= imem_wptr + 1'b1;                  // IMEM_DATA
                    6'h02: dbg_vsram_en <= la_wdata[0];                    // 0x08 DEBUG_CTRL
                    6'h03: dbg_row <= la_wdata[ON_CHIP_ADDR_WIDTH-1:0];    // 0x0C DEBUG_ADDR
                    6'h04: imem_wptr <= la_wdata[IMEM_ADDR_W-1:0];         // 0x10 IMEM_WPTR
                    6'h05: begin soft_rst_pulse <= 1'b1; imem_wptr <= '0; end // 0x14 SOFT_RST
                    6'h07: ddr3_addr_q          <= la_wdata[AXI_ADDR_W-1:0];  // 0x1C DDR3_ADDR
                    6'h08: ddr3_wbeat_q[31:0]   <= la_wdata;                  // 0x20 DDR3_W0
                    6'h09: ddr3_wbeat_q[63:32]  <= la_wdata;                  // 0x24 DDR3_W1
                    6'h0A: ddr3_wbeat_q[95:64]  <= la_wdata;                  // 0x28 DDR3_W2
                    6'h0B: ddr3_wbeat_q[127:96] <= la_wdata;                  // 0x2C DDR3_W3
                    6'h0C: ddr3_go_pulse <= 1'b1;                             // 0x30 DDR3_GO (write beat)
                    6'h0E: load_mode     <= la_wdata[0];                      // 0x38 LOAD_MODE
                    6'h0F: ddr3_rd_pulse <= 1'b1;                             // 0x3C DDR3_RD (read beat)
                    default: ;
                endcase
            end
        end
    end

    // ---- Read channel ----
    logic        rvalid_r;
    logic [31:0] rdata_r;
    wire         rd_fire = la_arvalid & la_arready;
    wire  [5:0]  rd_w    = la_araddr[7:2];
    assign la_arready = ~rvalid_r;
    assign la_rvalid  = rvalid_r;
    assign la_rresp   = 2'b00;
    assign la_rdata   = rdata_r;

    always_ff @(posedge plena_clk) begin
        if (core_rst) begin
            rvalid_r <= 1'b0; rdata_r <= 32'h0;
        end else if (rd_fire) begin
            rvalid_r <= 1'b1;
            case (rd_w)
                6'h01:   rdata_r <= {30'b0, init_calib_complete_sync, system_break_latched}; // 0x04 STATUS
                6'h04:   rdata_r <= {{(32-IMEM_ADDR_W){1'b0}}, imem_wptr};      // 0x10 IMEM_WPTR
                6'h05:   rdata_r <= free_run;                                   // 0x14 FREE_RUN
                6'h06:   rdata_r <= rst_cnt;                                    // 0x18 RST_CNT
                6'h07:   rdata_r <= {{(32-AXI_ADDR_W){1'b0}}, ddr3_addr_q};     // 0x1C DDR3_ADDR
                6'h08:   rdata_r <= ddr3_rbeat_q[31:0];                         // 0x20 DDR3_R0
                6'h09:   rdata_r <= ddr3_rbeat_q[63:32];                        // 0x24 DDR3_R1
                6'h0A:   rdata_r <= ddr3_rbeat_q[95:64];                        // 0x28 DDR3_R2
                6'h0B:   rdata_r <= ddr3_rbeat_q[127:96];                       // 0x2C DDR3_R3
                6'h0D:   rdata_r <= {30'b0, loader_done, loader_busy};          // 0x34 DDR3_STATUS
                6'h0E:   rdata_r <= {31'b0, load_mode};                         // 0x38 LOAD_MODE
                default: rdata_r <= (rd_w >= 6'h10 && rd_w < 6'h10 + DBG_WORDS)
                                    ? dbg_cap[(rd_w - 6'h10)*32 +: 32] : 32'h0; // 0x40.. DEBUG_Dk
            endcase
        end else if (la_rready) begin
            rvalid_r <= 1'b0;
        end
    end

    // ---- Loader FSM: on GO (write) / RD (read), issue one 128-bit PutFullData / Get on the loader
    // link into the shared tl_to_axi4 bridge (single outstanding, muxed in below). On dp_rst so it
    // is live while the core is held in reset. ----
    wire                       ldr_a_ready;   // from the 2:1 bridge-input mux (below)
    wire                       ldr_d_valid;
    logic                      ldr_a_valid;
    logic [2:0]                ldr_a_opcode;
    logic [HBM_ADDR_WIDTH-1:0] ldr_a_address;
    logic [BRIDGE_DATA_W-1:0]  ldr_a_data;
    logic                      ldr_d_ready;
    typedef enum logic [1:0] {LD_IDLE, LD_REQ, LD_RESP} lstate_t;
    lstate_t lstate;
    always_ff @(posedge plena_clk) begin
        if (dp_rst) begin
            lstate <= LD_IDLE; ldr_a_valid <= 1'b0; ldr_a_opcode <= '0;
            ldr_a_address <= '0; ldr_a_data <= '0; ldr_d_ready <= 1'b0;
            loader_busy <= 1'b0; loader_done <= 1'b0; ddr3_rbeat_q <= '0;
        end else begin
            case (lstate)
                LD_IDLE: if (ddr3_go_pulse || ddr3_rd_pulse) begin
                    loader_busy   <= 1'b1; loader_done <= 1'b0;
                    ldr_a_valid   <= 1'b1;
                    ldr_a_opcode  <= ddr3_go_pulse ? 3'd0 : 3'd4;   // PutFullData : Get
                    ldr_a_address <= {{(HBM_ADDR_WIDTH-AXI_ADDR_W){1'b0}}, ddr3_addr_q};
                    ldr_a_data    <= ddr3_wbeat_q[BRIDGE_DATA_W-1:0];
                    lstate        <= LD_REQ;
                end
                LD_REQ: if (ldr_a_ready) begin ldr_a_valid <= 1'b0; ldr_d_ready <= 1'b1; lstate <= LD_RESP; end
                LD_RESP: if (ldr_d_valid) begin
                    ddr3_rbeat_q <= bridge_d_data;   // meaningful for a Get; ignored for a write
                    ldr_d_ready  <= 1'b0; loader_busy <= 1'b0; loader_done <= 1'b1;
                    lstate       <= LD_IDLE;
                end
                default: lstate <= LD_IDLE;
            endcase
        end
    end

    // ---- JTAG-to-AXI master: custom BSCANE2 -> jtag_axi_bscan (Vivado-free). Driven from a host
    // by pyftdi/OpenOCD over the FT2232H JTAG cable -- no jtag_axi IP, no hw_server. On BSCANE2,
    // TDI is a primitive OUTPUT (host->fabric serial data) and TDO its only INPUT (fabric->host);
    // JTAG_CHAIN=4 => USER4 (host IR opcode 0x23). Validated in sim via jtag_axi_bscan + SimTopA7_jtag. ----
    wire tap_tck, tap_sel, tap_capture, tap_shift, tap_update, tap_reset, tap_tdi, tap_tdo;
    BSCANE2 #(.JTAG_CHAIN(4)) u_bscan (
        .CAPTURE(tap_capture), .DRCK(), .RESET(tap_reset), .RUNTEST(),
        .SEL(tap_sel), .SHIFT(tap_shift), .TCK(tap_tck), .TDI(tap_tdi),
        .TMS(), .UPDATE(tap_update), .TDO(tap_tdo)
    );
    jtag_axi_bscan #(.ADDR_W(7), .DATA_W(32)) u_jtag_axi (
        .tck(tap_tck), .tap_reset(tap_reset), .sel(tap_sel), .capture(tap_capture),
        .shift(tap_shift), .update(tap_update), .tdi(tap_tdi), .tdo(tap_tdo),
        .aclk(plena_clk), .aresetn(~core_rst),
        .m_awaddr (la_awaddr), .m_awvalid(la_awvalid), .m_awready(la_awready),
        .m_wdata  (la_wdata),  .m_wstrb  (la_wstrb),   .m_wvalid (la_wvalid), .m_wready (la_wready),
        .m_bresp  (la_bresp),  .m_bvalid (la_bvalid),  .m_bready (la_bready),
        .m_araddr (la_araddr), .m_arvalid(la_arvalid), .m_arready(la_arready),
        .m_rdata  (la_rdata),  .m_rresp  (la_rresp),   .m_rvalid (la_rvalid), .m_rready (la_rready)
    );

    // =========================================================
    // Per-channel skid buffers -> round-robin arbiter -> per-channel response FIFOs ->
    // single tl_to_axi4 bridge -> MIG DDR3. The naive strict-priority mux (a_ready =
    // active&&bridge_ready, no buffering) DEADLOCKS three ways: (1) it only grants a_ready to
    // an already-arbitrated channel while plena gates a_valid on a_ready; (2) the single-
    // outstanding bridge stalls in TL_RESP holding one channel's response until plena consumes
    // it, but plena holds it pending its join2 partner (element<->scale) whose read is queued
    // behind the stalled bridge; (3) strict priority drains a whole element burst (matrix
    // LOAD_AMOUNT=MLEN) before any scale, which the join needs paired. Fix: tl_regslice skid
    // buffers (a_ready=!full), per-channel response FIFOs (bridge never back-pressured), and
    // round-robin so element/scale interleave. Validated in SimTopDDR against a behavioural DDR3.
    // =========================================================
    `TL_DECLARE(HBM_ELE_WIDTH,   HBM_ADDR_WIDTH, SourceWidth, SinkWidth, m_element_r);
    `TL_DECLARE(HBM_SCALE_WIDTH, HBM_ADDR_WIDTH, SourceWidth, SinkWidth, m_scale_r);
    `TL_DECLARE(HBM_ELE_WIDTH,   HBM_ADDR_WIDTH, SourceWidth, SinkWidth, v_element_r);
    `TL_DECLARE(HBM_SCALE_WIDTH, HBM_ADDR_WIDTH, SourceWidth, SinkWidth, v_scale_r);

    tl_regslice #(.SourceWidth(SourceWidth), .SinkWidth(SinkWidth), .AddrWidth(HBM_ADDR_WIDTH), .DataWidth(HBM_ELE_WIDTH),   .RequestMode(7)) rs_m_ele (.clk_i(plena_clk), .rst_ni(!dp_rst), `TL_CONNECT_DEVICE_PORT(host, m_element), `TL_CONNECT_HOST_PORT(device, m_element_r));
    tl_regslice #(.SourceWidth(SourceWidth), .SinkWidth(SinkWidth), .AddrWidth(HBM_ADDR_WIDTH), .DataWidth(HBM_SCALE_WIDTH), .RequestMode(7)) rs_m_sc  (.clk_i(plena_clk), .rst_ni(!dp_rst), `TL_CONNECT_DEVICE_PORT(host, m_scale),   `TL_CONNECT_HOST_PORT(device, m_scale_r));
    tl_regslice #(.SourceWidth(SourceWidth), .SinkWidth(SinkWidth), .AddrWidth(HBM_ADDR_WIDTH), .DataWidth(HBM_ELE_WIDTH),   .RequestMode(7)) rs_v_ele (.clk_i(plena_clk), .rst_ni(!dp_rst), `TL_CONNECT_DEVICE_PORT(host, v_element), `TL_CONNECT_HOST_PORT(device, v_element_r));
    tl_regslice #(.SourceWidth(SourceWidth), .SinkWidth(SinkWidth), .AddrWidth(HBM_ADDR_WIDTH), .DataWidth(HBM_SCALE_WIDTH), .RequestMode(7)) rs_v_sc  (.clk_i(plena_clk), .rst_ni(!dp_rst), `TL_CONNECT_DEVICE_PORT(host, v_scale),   `TL_CONNECT_HOST_PORT(device, v_scale_r));

    localparam logic [1:0] CH_M_ELE = 2'd0, CH_M_SC = 2'd1, CH_V_ELE = 2'd2, CH_V_SC = 2'd3;

    wire bridge_a_ready;
    wire any_a_valid = m_element_r_a_valid | m_scale_r_a_valid | v_element_r_a_valid | v_scale_r_a_valid;
    wire plena_bridge_a_ready = bridge_a_ready & ~load_mode;   // plena mux is gated off during JTAG DDR3 load

    // Round-robin arbiter (bit0=m_ele bit1=m_sc bit2=v_ele bit3=v_sc).
    wire [3:0] rr_req = {v_scale_r_a_valid, v_element_r_a_valid, m_scale_r_a_valid, m_element_r_a_valid};
    reg  [1:0] rr_ptr;
    logic [1:0] active_ch;
    always_comb begin
        if      (rr_req[rr_ptr])       active_ch = rr_ptr;
        else if (rr_req[rr_ptr+2'd1])  active_ch = rr_ptr + 2'd1;
        else if (rr_req[rr_ptr+2'd2])  active_ch = rr_ptr + 2'd2;
        else                           active_ch = rr_ptr + 2'd3;
    end
    always_ff @(posedge plena_clk) begin
        if (dp_rst)                          rr_ptr <= 2'd0;
        else if (any_a_valid && plena_bridge_a_ready) rr_ptr <= active_ch + 2'd1;
    end

    logic [2:0]                a_opcode_mux;
    logic [SourceWidth-1:0]    a_source_mux;
    logic [HBM_ADDR_WIDTH-1:0] a_address_mux;
    logic [BRIDGE_DATA_W-1:0]  a_data_mux;
    always_comb begin
        a_opcode_mux  = '0;
        a_source_mux  = '0;
        a_address_mux = '0;
        a_data_mux    = '0;
        unique case (active_ch)
            CH_M_ELE: begin
                a_opcode_mux  = m_element_r_a.opcode;
                a_source_mux  = m_element_r_a.source;
                a_address_mux = m_element_r_a.address;
                a_data_mux[HBM_ELE_WIDTH-1:0] = m_element_r_a.data;
            end
            CH_M_SC: begin
                a_opcode_mux  = m_scale_r_a.opcode;
                a_source_mux  = m_scale_r_a.source;
                a_address_mux = m_scale_r_a.address;
                a_data_mux[HBM_SCALE_WIDTH-1:0] = m_scale_r_a.data;
            end
            CH_V_ELE: begin
                a_opcode_mux  = v_element_r_a.opcode;
                a_source_mux  = v_element_r_a.source;
                a_address_mux = v_element_r_a.address;
                a_data_mux[HBM_ELE_WIDTH-1:0] = v_element_r_a.data;
            end
            CH_V_SC: begin
                a_opcode_mux  = v_scale_r_a.opcode;
                a_source_mux  = v_scale_r_a.source;
                a_address_mux = v_scale_r_a.address;
                a_data_mux[HBM_SCALE_WIDTH-1:0] = v_scale_r_a.data;
            end
        endcase
    end

    assign m_element_r_a_ready = (active_ch == CH_M_ELE) && plena_bridge_a_ready;
    assign m_scale_r_a_ready   = (active_ch == CH_M_SC)  && plena_bridge_a_ready;
    assign v_element_r_a_ready = (active_ch == CH_V_ELE) && plena_bridge_a_ready;
    assign v_scale_r_a_ready   = (active_ch == CH_V_SC)  && plena_bridge_a_ready;

    // Remember which channel owns the in-flight (single-outstanding) request.
    reg [1:0] resp_ch;
    always @(posedge plena_clk) begin
        if (dp_rst)
            resp_ch <= CH_M_ELE;
        else if (any_a_valid && plena_bridge_a_ready)
            resp_ch <= active_ch;
    end

    wire                      bridge_d_valid;
    wire [BRIDGE_DATA_W-1:0]  bridge_d_data;
    wire                      bridge_d_error;
    wire [SourceWidth-1:0]    bridge_d_source;
    wire plena_bridge_d_valid = bridge_d_valid & ~load_mode;   // FIFOs ignore the loader's response

    // Per-channel response FIFOs (Pass=0 => wready=!full, decoupled). The single-outstanding
    // bridge always drains its response into the owning channel's FIFO and is never back-
    // pressured, so it can immediately service the join partner's queued read. Depth 32 >
    // matrix LOAD_AMOUNT(MLEN). FIFO word = {denied, source, data}.
    localparam int ELE_FW = 1 + SourceWidth + HBM_ELE_WIDTH;
    localparam int SC_FW  = 1 + SourceWidth + HBM_SCALE_WIDTH;

    wire fifo_mele_wr, fifo_msc_wr, fifo_vele_wr, fifo_vsc_wr;
    wire plena_bridge_d_ready = (resp_ch == CH_M_ELE) ? fifo_mele_wr :
                          (resp_ch == CH_M_SC)  ? fifo_msc_wr  :
                          (resp_ch == CH_V_ELE) ? fifo_vele_wr : fifo_vsc_wr;

    wire [ELE_FW-1:0] mele_rd, vele_rd;
    wire [SC_FW-1:0]  msc_rd,  vsc_rd;

    prim_fifo_sync #(.Width(ELE_FW), .Pass(1'b0), .Depth(32)) rf_mele (
        .clk_i(plena_clk), .rst_ni(!dp_rst), .clr_i(1'b0),
        .wvalid_i(plena_bridge_d_valid && (resp_ch==CH_M_ELE)), .wready_o(fifo_mele_wr),
        .wdata_i({bridge_d_error, bridge_d_source, bridge_d_data[HBM_ELE_WIDTH-1:0]}),
        .rvalid_o(m_element_r_d_valid), .rready_i(m_element_r_d_ready), .rdata_o(mele_rd),
        .full_o(), .depth_o(), .err_o());
    assign m_element_r_d.opcode=tl_pkg::AccessAckData; assign m_element_r_d.param='0; assign m_element_r_d.sink='0;
    assign m_element_r_d.size=`TL_SIZE_WIDTH'($clog2(HBM_ELE_WIDTH/8)); assign m_element_r_d.source=mele_rd[HBM_ELE_WIDTH +: SourceWidth];
    assign m_element_r_d.denied=mele_rd[ELE_FW-1]; assign m_element_r_d.corrupt=mele_rd[ELE_FW-1]; assign m_element_r_d.data=mele_rd[HBM_ELE_WIDTH-1:0];

    prim_fifo_sync #(.Width(SC_FW), .Pass(1'b0), .Depth(32)) rf_msc (
        .clk_i(plena_clk), .rst_ni(!dp_rst), .clr_i(1'b0),
        .wvalid_i(plena_bridge_d_valid && (resp_ch==CH_M_SC)), .wready_o(fifo_msc_wr),
        .wdata_i({bridge_d_error, bridge_d_source, bridge_d_data[HBM_SCALE_WIDTH-1:0]}),
        .rvalid_o(m_scale_r_d_valid), .rready_i(m_scale_r_d_ready), .rdata_o(msc_rd),
        .full_o(), .depth_o(), .err_o());
    assign m_scale_r_d.opcode=tl_pkg::AccessAckData; assign m_scale_r_d.param='0; assign m_scale_r_d.sink='0;
    assign m_scale_r_d.size=`TL_SIZE_WIDTH'($clog2(HBM_SCALE_WIDTH/8)); assign m_scale_r_d.source=msc_rd[HBM_SCALE_WIDTH +: SourceWidth];
    assign m_scale_r_d.denied=msc_rd[SC_FW-1]; assign m_scale_r_d.corrupt=msc_rd[SC_FW-1]; assign m_scale_r_d.data=msc_rd[HBM_SCALE_WIDTH-1:0];

    prim_fifo_sync #(.Width(ELE_FW), .Pass(1'b0), .Depth(32)) rf_vele (
        .clk_i(plena_clk), .rst_ni(!dp_rst), .clr_i(1'b0),
        .wvalid_i(plena_bridge_d_valid && (resp_ch==CH_V_ELE)), .wready_o(fifo_vele_wr),
        .wdata_i({bridge_d_error, bridge_d_source, bridge_d_data[HBM_ELE_WIDTH-1:0]}),
        .rvalid_o(v_element_r_d_valid), .rready_i(v_element_r_d_ready), .rdata_o(vele_rd),
        .full_o(), .depth_o(), .err_o());
    assign v_element_r_d.opcode=tl_pkg::AccessAckData; assign v_element_r_d.param='0; assign v_element_r_d.sink='0;
    assign v_element_r_d.size=`TL_SIZE_WIDTH'($clog2(HBM_ELE_WIDTH/8)); assign v_element_r_d.source=vele_rd[HBM_ELE_WIDTH +: SourceWidth];
    assign v_element_r_d.denied=vele_rd[ELE_FW-1]; assign v_element_r_d.corrupt=vele_rd[ELE_FW-1]; assign v_element_r_d.data=vele_rd[HBM_ELE_WIDTH-1:0];

    prim_fifo_sync #(.Width(SC_FW), .Pass(1'b0), .Depth(32)) rf_vsc (
        .clk_i(plena_clk), .rst_ni(!dp_rst), .clr_i(1'b0),
        .wvalid_i(plena_bridge_d_valid && (resp_ch==CH_V_SC)), .wready_o(fifo_vsc_wr),
        .wdata_i({bridge_d_error, bridge_d_source, bridge_d_data[HBM_SCALE_WIDTH-1:0]}),
        .rvalid_o(v_scale_r_d_valid), .rready_i(v_scale_r_d_ready), .rdata_o(vsc_rd),
        .full_o(), .depth_o(), .err_o());
    assign v_scale_r_d.opcode=tl_pkg::AccessAckData; assign v_scale_r_d.param='0; assign v_scale_r_d.sink='0;
    assign v_scale_r_d.size=`TL_SIZE_WIDTH'($clog2(HBM_SCALE_WIDTH/8)); assign v_scale_r_d.source=vsc_rd[HBM_SCALE_WIDTH +: SourceWidth];
    assign v_scale_r_d.denied=vsc_rd[SC_FW-1]; assign v_scale_r_d.corrupt=vsc_rd[SC_FW-1]; assign v_scale_r_d.data=vsc_rd[HBM_SCALE_WIDTH-1:0];

    // Unused TL-UH channels on the registered (mux-side) links.
    assign m_element_r_b_valid = 1'b0; assign m_element_r_b = '0;
    assign m_element_r_c_ready = 1'b1; assign m_element_r_e_ready = 1'b1;
    assign m_scale_r_b_valid   = 1'b0; assign m_scale_r_b = '0;
    assign m_scale_r_c_ready   = 1'b1; assign m_scale_r_e_ready = 1'b1;
    assign v_element_r_b_valid = 1'b0; assign v_element_r_b = '0;
    assign v_element_r_c_ready = 1'b1; assign v_element_r_e_ready = 1'b1;
    assign v_scale_r_b_valid   = 1'b0; assign v_scale_r_b = '0;
    assign v_scale_r_c_ready   = 1'b1; assign v_scale_r_e_ready = 1'b1;

    // ---- 2:1 mux at the bridge input: the JTAG loader owns the shared bridge while load_mode=1
    // (core held in reset, plena mux gated off); otherwise the plena 4-way mux drives it. ----
    wire                      sel_a_valid   = load_mode ? ldr_a_valid   : any_a_valid;
    wire [2:0]                sel_a_opcode  = load_mode ? ldr_a_opcode  : a_opcode_mux;
    wire [SourceWidth-1:0]    sel_a_source  = load_mode ? '0            : a_source_mux;
    wire [HBM_ADDR_WIDTH-1:0] sel_a_address = load_mode ? ldr_a_address : a_address_mux;
    wire [BRIDGE_DATA_W-1:0]  sel_a_data    = load_mode ? ldr_a_data    : a_data_mux;
    assign ldr_a_ready = bridge_a_ready & load_mode;
    assign ldr_d_valid = bridge_d_valid & load_mode;
    wire sel_d_ready   = load_mode ? ldr_d_ready : plena_bridge_d_ready;

    // ---- AXI master <-> MIG slave wires ----
    wire [AXI_ID_W-1:0]   axi_awid,  axi_arid,  axi_bid,  axi_rid;
    wire [AXI_ADDR_W-1:0] axi_awaddr, axi_araddr;
    wire [7:0]            axi_awlen,  axi_arlen;
    wire [2:0]            axi_awsize, axi_arsize;
    wire [1:0]            axi_awburst, axi_arburst;
    wire                  axi_awvalid, axi_awready, axi_arvalid, axi_arready;
    wire [AXI_DATA_W-1:0] axi_wdata,  axi_rdata;
    wire [AXI_STRB_W-1:0] axi_wstrb;
    wire                  axi_wlast,  axi_wvalid, axi_wready;
    wire [1:0]            axi_bresp,  axi_rresp;
    wire                  axi_bvalid, axi_bready, axi_rlast, axi_rvalid, axi_rready;

    tl_to_axi4 #(
        .ADDR_W(HBM_ADDR_WIDTH), .DATA_W(BRIDGE_DATA_W),
        .SOURCE_W(SourceWidth), .SINK_W(SinkWidth),
        .AXI_ID_W(AXI_ID_W), .AXI_ADDR_W(AXI_ADDR_W), .AXI_DATA_W(AXI_DATA_W)
    ) u_bridge (
        .clk(plena_clk), .rst(dp_rst),
        .tl_a_valid(sel_a_valid), .tl_a_ready(bridge_a_ready),
        .tl_a_opcode(sel_a_opcode), .tl_a_size(BRIDGE_TL_SIZE),
        .tl_a_source(sel_a_source), .tl_a_address(sel_a_address),
        .tl_a_mask({BRIDGE_MASK_W{1'b1}}), .tl_a_data(sel_a_data),
        .tl_d_valid(bridge_d_valid), .tl_d_ready(sel_d_ready),
        .tl_d_opcode(), .tl_d_size(), .tl_d_source(bridge_d_source), .tl_d_sink(),
        .tl_d_data(bridge_d_data), .tl_d_error(bridge_d_error),
        .m_axi_awid(axi_awid), .m_axi_awaddr(axi_awaddr),
        .m_axi_awlen(axi_awlen), .m_axi_awsize(axi_awsize),
        .m_axi_awburst(axi_awburst), .m_axi_awvalid(axi_awvalid), .m_axi_awready(axi_awready),
        .m_axi_wdata(axi_wdata), .m_axi_wstrb(axi_wstrb),
        .m_axi_wlast(axi_wlast), .m_axi_wvalid(axi_wvalid), .m_axi_wready(axi_wready),
        .m_axi_bid(axi_bid), .m_axi_bresp(axi_bresp),
        .m_axi_bvalid(axi_bvalid), .m_axi_bready(axi_bready),
        .m_axi_arid(axi_arid), .m_axi_araddr(axi_araddr),
        .m_axi_arlen(axi_arlen), .m_axi_arsize(axi_arsize),
        .m_axi_arburst(axi_arburst), .m_axi_arvalid(axi_arvalid), .m_axi_arready(axi_arready),
        .m_axi_rid(axi_rid), .m_axi_rdata(axi_rdata),
        .m_axi_rresp(axi_rresp), .m_axi_rlast(axi_rlast),
        .m_axi_rvalid(axi_rvalid), .m_axi_rready(axi_rready)
    );

    // =========================================================
    // AXI clock-domain crossing: tl_to_axi4 runs in the 50 MHz core_clk domain, the MIG s_axi
    // in the 100 MHz ui_clk domain. One axi_clock_converter bridges the two. This is the ONLY
    // CDC on the datapath (plus the reset/calib single-bit syncs above).
    // =========================================================
    wire [AXI_ID_W-1:0]   maxi_awid,  maxi_arid,  maxi_bid,  maxi_rid;
    wire [AXI_ADDR_W-1:0] maxi_awaddr, maxi_araddr;
    wire [7:0]            maxi_awlen,  maxi_arlen;
    wire [2:0]            maxi_awsize, maxi_arsize;
    wire [1:0]            maxi_awburst, maxi_arburst;
    wire                  maxi_awlock, maxi_arlock;
    wire [3:0]            maxi_awcache, maxi_arcache;
    wire [2:0]            maxi_awprot, maxi_arprot;
    wire [3:0]            maxi_awqos,  maxi_arqos;
    wire                  maxi_awvalid, maxi_awready, maxi_arvalid, maxi_arready;
    wire [AXI_DATA_W-1:0] maxi_wdata,  maxi_rdata;
    wire [AXI_STRB_W-1:0] maxi_wstrb;
    wire                  maxi_wlast,  maxi_wvalid, maxi_wready;
    wire [1:0]            maxi_bresp,  maxi_rresp;
    wire                  maxi_bvalid, maxi_bready, maxi_rlast, maxi_rvalid, maxi_rready;

    axi_clock_converter_0 u_axi_cdc (
        // Slave side: core_clk (50 MHz), from tl_to_axi4. Tie off the AXI4 qualifiers tl_to_axi4
        // does not drive (previously hardcoded at the MIG port).
        .s_axi_aclk(plena_clk), .s_axi_aresetn(~core_rst),
        .s_axi_awid(axi_awid), .s_axi_awaddr(axi_awaddr), .s_axi_awlen(axi_awlen),
        .s_axi_awsize(axi_awsize), .s_axi_awburst(axi_awburst), .s_axi_awlock(1'b0),
        .s_axi_awcache(4'b0011), .s_axi_awprot(3'b000), .s_axi_awregion(4'b0000), .s_axi_awqos(4'b0000),
        .s_axi_awvalid(axi_awvalid), .s_axi_awready(axi_awready),
        .s_axi_wdata(axi_wdata), .s_axi_wstrb(axi_wstrb), .s_axi_wlast(axi_wlast),
        .s_axi_wvalid(axi_wvalid), .s_axi_wready(axi_wready),
        .s_axi_bid(axi_bid), .s_axi_bresp(axi_bresp), .s_axi_bvalid(axi_bvalid), .s_axi_bready(axi_bready),
        .s_axi_arid(axi_arid), .s_axi_araddr(axi_araddr), .s_axi_arlen(axi_arlen),
        .s_axi_arsize(axi_arsize), .s_axi_arburst(axi_arburst), .s_axi_arlock(1'b0),
        .s_axi_arcache(4'b0011), .s_axi_arprot(3'b000), .s_axi_arregion(4'b0000), .s_axi_arqos(4'b0000),
        .s_axi_arvalid(axi_arvalid), .s_axi_arready(axi_arready),
        .s_axi_rid(axi_rid), .s_axi_rdata(axi_rdata), .s_axi_rresp(axi_rresp),
        .s_axi_rlast(axi_rlast), .s_axi_rvalid(axi_rvalid), .s_axi_rready(axi_rready),
        // Master side: ui_clk (100 MHz), to the MIG.
        .m_axi_aclk(ui_clk), .m_axi_aresetn(~ui_clk_sync_rst),
        .m_axi_awid(maxi_awid), .m_axi_awaddr(maxi_awaddr), .m_axi_awlen(maxi_awlen),
        .m_axi_awsize(maxi_awsize), .m_axi_awburst(maxi_awburst), .m_axi_awlock(maxi_awlock),
        .m_axi_awcache(maxi_awcache), .m_axi_awprot(maxi_awprot), .m_axi_awregion(), .m_axi_awqos(maxi_awqos),
        .m_axi_awvalid(maxi_awvalid), .m_axi_awready(maxi_awready),
        .m_axi_wdata(maxi_wdata), .m_axi_wstrb(maxi_wstrb), .m_axi_wlast(maxi_wlast),
        .m_axi_wvalid(maxi_wvalid), .m_axi_wready(maxi_wready),
        .m_axi_bid(maxi_bid), .m_axi_bresp(maxi_bresp), .m_axi_bvalid(maxi_bvalid), .m_axi_bready(maxi_bready),
        .m_axi_arid(maxi_arid), .m_axi_araddr(maxi_araddr), .m_axi_arlen(maxi_arlen),
        .m_axi_arsize(maxi_arsize), .m_axi_arburst(maxi_arburst), .m_axi_arlock(maxi_arlock),
        .m_axi_arcache(maxi_arcache), .m_axi_arprot(maxi_arprot), .m_axi_arregion(), .m_axi_arqos(maxi_arqos),
        .m_axi_arvalid(maxi_arvalid), .m_axi_arready(maxi_arready),
        .m_axi_rid(maxi_rid), .m_axi_rdata(maxi_rdata), .m_axi_rresp(maxi_rresp),
        .m_axi_rlast(maxi_rlast), .m_axi_rvalid(maxi_rvalid), .m_axi_rready(maxi_rready)
    );

    // LEDs (debug)
    assign led[0] = system_break;
    assign led[1] = m_element_a_valid;
    assign led[2] = v_element_a_valid;
    assign led[3] = init_calib_complete;
    assign led[4] = axi_awvalid | axi_arvalid;
    assign led[6:5] = 2'b0;

    // =========================================================
    // MIG DDR3 controller (Vivado IP from mig_nexys_video.prj)
    // =========================================================
    mig_ddr3 u_mig (
        .ddr3_addr(ddr3_addr), .ddr3_ba(ddr3_ba),
        .ddr3_cas_n(ddr3_cas_n), .ddr3_ck_n(ddr3_ck_n), .ddr3_ck_p(ddr3_ck_p),
        .ddr3_cke(ddr3_cke), .ddr3_ras_n(ddr3_ras_n), .ddr3_reset_n(ddr3_reset_n),
        .ddr3_we_n(ddr3_we_n), .ddr3_dq(ddr3_dq),
        .ddr3_dqs_n(ddr3_dqs_n), .ddr3_dqs_p(ddr3_dqs_p),
        .ddr3_dm(ddr3_dm), .ddr3_odt(ddr3_odt),
        .s_axi_awid(maxi_awid), .s_axi_awaddr(maxi_awaddr),
        .s_axi_awlen(maxi_awlen), .s_axi_awsize(maxi_awsize),
        .s_axi_awburst(maxi_awburst), .s_axi_awlock(maxi_awlock),
        .s_axi_awcache(maxi_awcache), .s_axi_awprot(maxi_awprot), .s_axi_awqos(maxi_awqos),
        .s_axi_awvalid(maxi_awvalid), .s_axi_awready(maxi_awready),
        .s_axi_wdata(maxi_wdata), .s_axi_wstrb(maxi_wstrb),
        .s_axi_wlast(maxi_wlast), .s_axi_wvalid(maxi_wvalid), .s_axi_wready(maxi_wready),
        .s_axi_bid(maxi_bid), .s_axi_bresp(maxi_bresp),
        .s_axi_bvalid(maxi_bvalid), .s_axi_bready(maxi_bready),
        .s_axi_arid(maxi_arid), .s_axi_araddr(maxi_araddr),
        .s_axi_arlen(maxi_arlen), .s_axi_arsize(maxi_arsize),
        .s_axi_arburst(maxi_arburst), .s_axi_arlock(maxi_arlock),
        .s_axi_arcache(maxi_arcache), .s_axi_arprot(maxi_arprot), .s_axi_arqos(maxi_arqos),
        .s_axi_arvalid(maxi_arvalid), .s_axi_arready(maxi_arready),
        .s_axi_rid(maxi_rid), .s_axi_rdata(maxi_rdata),
        .s_axi_rresp(maxi_rresp), .s_axi_rlast(maxi_rlast),
        .s_axi_rvalid(maxi_rvalid), .s_axi_rready(maxi_rready),
        .sys_clk_i(sys_clk),
        .clk_ref_i(sys_clk_bufg),
        .sys_rst(sys_rst_n),
        .ui_clk(ui_clk),
        .ui_addn_clk_0(ui_addn_clk_0),
        .ui_clk_sync_rst(ui_clk_sync_rst),
        .aresetn(~ui_clk_sync_rst),
        .app_sr_req(1'b0),
        .app_ref_req(1'b0),
        .app_zq_req(1'b0),
        .init_calib_complete(init_calib_complete)
    );

endmodule
