// Xilinx primitive / IP black-box stubs for Verilator lint & simulation ONLY.
// Guarded by `ifdef VERILATOR so this file is empty under Vivado synthesis, where the
// real BUFG primitive and the MIG-generated mig_ddr3 IP are used instead. Do NOT add this
// file to the Vivado build (build_nexys.tcl does not).
`ifdef VERILATOR

module BUFG (input wire I, output wire O);
    assign O = I;
endmodule

// Black-box model of the MIG 7-series DDR3 AXI slave (mig_nexys_video.prj).
// Ports/widths match the plena_a7_top instantiation; outputs are tied to 0 — this only
// lets the top elaborate for lint, it does not model DDR behaviour.
module mig_ddr3 (
    output wire [14:0] ddr3_addr,
    output wire [2:0]  ddr3_ba,
    output wire        ddr3_cas_n, ddr3_ck_n, ddr3_ck_p, ddr3_cke,
    output wire        ddr3_ras_n, ddr3_reset_n, ddr3_we_n,
    inout  wire [15:0] ddr3_dq,
    inout  wire [1:0]  ddr3_dqs_n, ddr3_dqs_p,
    output wire [1:0]  ddr3_dm,
    output wire        ddr3_odt,

    input  wire [3:0]   s_axi_awid,
    input  wire [28:0]  s_axi_awaddr,
    input  wire [7:0]   s_axi_awlen,
    input  wire [2:0]   s_axi_awsize,
    input  wire [1:0]   s_axi_awburst,
    input  wire         s_axi_awlock,
    input  wire [3:0]   s_axi_awcache,
    input  wire [2:0]   s_axi_awprot,
    input  wire [3:0]   s_axi_awqos,
    input  wire         s_axi_awvalid,
    output wire         s_axi_awready,
    input  wire [127:0] s_axi_wdata,
    input  wire [15:0]  s_axi_wstrb,
    input  wire         s_axi_wlast,
    input  wire         s_axi_wvalid,
    output wire         s_axi_wready,
    output wire [3:0]   s_axi_bid,
    output wire [1:0]   s_axi_bresp,
    output wire         s_axi_bvalid,
    input  wire         s_axi_bready,
    input  wire [3:0]   s_axi_arid,
    input  wire [28:0]  s_axi_araddr,
    input  wire [7:0]   s_axi_arlen,
    input  wire [2:0]   s_axi_arsize,
    input  wire [1:0]   s_axi_arburst,
    input  wire         s_axi_arlock,
    input  wire [3:0]   s_axi_arcache,
    input  wire [2:0]   s_axi_arprot,
    input  wire [3:0]   s_axi_arqos,
    input  wire         s_axi_arvalid,
    output wire         s_axi_arready,
    output wire [3:0]   s_axi_rid,
    output wire [127:0] s_axi_rdata,
    output wire [1:0]   s_axi_rresp,
    output wire         s_axi_rlast,
    output wire         s_axi_rvalid,
    input  wire         s_axi_rready,

    input  wire sys_clk_i,
    input  wire clk_ref_i,
    input  wire sys_rst,
    output wire ui_clk,
    output wire ui_addn_clk_0,
    output wire ui_clk_sync_rst,
    input  wire aresetn,
    input  wire app_sr_req,
    input  wire app_ref_req,
    input  wire app_zq_req,
    output wire init_calib_complete
);
    assign ui_addn_clk_0 = sys_clk_i;   // lint-only: real MIG MMCM emits the 25 MHz core clock
    assign ddr3_addr = '0; assign ddr3_ba = '0;
    assign ddr3_cas_n = 1'b1; assign ddr3_ck_n = 1'b0; assign ddr3_ck_p = 1'b0;
    assign ddr3_cke = 1'b0; assign ddr3_ras_n = 1'b1; assign ddr3_reset_n = 1'b0;
    assign ddr3_we_n = 1'b1; assign ddr3_dm = '0; assign ddr3_odt = 1'b0;
    assign s_axi_awready = 1'b0; assign s_axi_wready = 1'b0;
    assign s_axi_bid = '0; assign s_axi_bresp = '0; assign s_axi_bvalid = 1'b0;
    assign s_axi_arready = 1'b0;
    assign s_axi_rid = '0; assign s_axi_rdata = '0; assign s_axi_rresp = '0;
    assign s_axi_rlast = 1'b0; assign s_axi_rvalid = 1'b0;
    // Drive the UI reset from sys_rst (a primary input), NOT from aresetn — the top ties
    // aresetn = ~ui_clk_sync_rst, so deriving it from aresetn would form a comb loop. The
    // real MIG generates ui_clk_sync_rst from its internal reset sequencer.
    assign ui_clk = sys_clk_i; assign ui_clk_sync_rst = ~sys_rst;
    assign init_calib_complete = 1'b1;
endmodule

// Lint/sim stub of the 7-series BSCANE2 JTAG primitive (the real unisim provides the JTAG tap in
// Vivado synthesis). Outputs idle so plena_a7_top elaborates without the JTAG tap.
module BSCANE2 #(
    parameter integer JTAG_CHAIN = 1,
    parameter DISABLE_JTAG = "FALSE"
) (
    output wire CAPTURE,
    output wire DRCK,
    output wire RESET,
    output wire RUNTEST,
    output wire SEL,
    output wire SHIFT,
    output wire TCK,
    output wire TDI,
    output wire TMS,
    output wire UPDATE,
    input  wire TDO
);
    assign CAPTURE = 1'b0; assign DRCK = 1'b0; assign RESET = 1'b0; assign RUNTEST = 1'b0;
    assign SEL = 1'b0; assign SHIFT = 1'b0; assign TCK = 1'b0; assign TDI = 1'b0;
    assign TMS = 1'b0; assign UPDATE = 1'b0;
    wire _unused_tdo = TDO;
endmodule

// Lint/sim stub of the Xilinx axi_clock_converter IP (real IP generated by build_nexys.tcl).
// Ports/widths match the plena_a7_top instantiation; outputs tied off so the top elaborates.
module axi_clock_converter_0 (
    input  wire         s_axi_aclk, s_axi_aresetn,
    input  wire [3:0]   s_axi_awid,   input wire [28:0] s_axi_awaddr,
    input  wire [7:0]   s_axi_awlen,  input wire [2:0]  s_axi_awsize,
    input  wire [1:0]   s_axi_awburst, input wire       s_axi_awlock,
    input  wire [3:0]   s_axi_awcache, input wire [2:0] s_axi_awprot,
    input  wire [3:0]   s_axi_awregion, input wire [3:0] s_axi_awqos,
    input  wire         s_axi_awvalid, output wire      s_axi_awready,
    input  wire [127:0] s_axi_wdata,  input wire [15:0] s_axi_wstrb,
    input  wire         s_axi_wlast,  input wire        s_axi_wvalid,
    output wire         s_axi_wready,
    output wire [3:0]   s_axi_bid,    output wire [1:0] s_axi_bresp,
    output wire         s_axi_bvalid, input wire        s_axi_bready,
    input  wire [3:0]   s_axi_arid,   input wire [28:0] s_axi_araddr,
    input  wire [7:0]   s_axi_arlen,  input wire [2:0]  s_axi_arsize,
    input  wire [1:0]   s_axi_arburst, input wire       s_axi_arlock,
    input  wire [3:0]   s_axi_arcache, input wire [2:0] s_axi_arprot,
    input  wire [3:0]   s_axi_arregion, input wire [3:0] s_axi_arqos,
    input  wire         s_axi_arvalid, output wire      s_axi_arready,
    output wire [3:0]   s_axi_rid,    output wire [127:0] s_axi_rdata,
    output wire [1:0]   s_axi_rresp,  output wire       s_axi_rlast,
    output wire         s_axi_rvalid, input wire        s_axi_rready,
    input  wire         m_axi_aclk, m_axi_aresetn,
    output wire [3:0]   m_axi_awid,   output wire [28:0] m_axi_awaddr,
    output wire [7:0]   m_axi_awlen,  output wire [2:0]  m_axi_awsize,
    output wire [1:0]   m_axi_awburst, output wire       m_axi_awlock,
    output wire [3:0]   m_axi_awcache, output wire [2:0] m_axi_awprot,
    output wire [3:0]   m_axi_awregion, output wire [3:0] m_axi_awqos,
    output wire         m_axi_awvalid, input wire        m_axi_awready,
    output wire [127:0] m_axi_wdata,  output wire [15:0] m_axi_wstrb,
    output wire         m_axi_wlast,  output wire        m_axi_wvalid,
    input  wire         m_axi_wready,
    input  wire [3:0]   m_axi_bid,    input wire [1:0]  m_axi_bresp,
    input  wire         m_axi_bvalid, output wire       m_axi_bready,
    output wire [3:0]   m_axi_arid,   output wire [28:0] m_axi_araddr,
    output wire [7:0]   m_axi_arlen,  output wire [2:0]  m_axi_arsize,
    output wire [1:0]   m_axi_arburst, output wire       m_axi_arlock,
    output wire [3:0]   m_axi_arcache, output wire [2:0] m_axi_arprot,
    output wire [3:0]   m_axi_arregion, output wire [3:0] m_axi_arqos,
    output wire         m_axi_arvalid, input wire        m_axi_arready,
    input  wire [3:0]   m_axi_rid,    input wire [127:0] m_axi_rdata,
    input  wire [1:0]   m_axi_rresp,  input wire        m_axi_rlast,
    input  wire         m_axi_rvalid, output wire       m_axi_rready
);
    assign s_axi_awready = 1'b0; assign s_axi_wready = 1'b0;
    assign s_axi_bid = '0; assign s_axi_bresp = '0; assign s_axi_bvalid = 1'b0;
    assign s_axi_arready = 1'b0;
    assign s_axi_rid = '0; assign s_axi_rdata = '0; assign s_axi_rresp = '0;
    assign s_axi_rlast = 1'b0; assign s_axi_rvalid = 1'b0;
    assign m_axi_awid = '0; assign m_axi_awaddr = '0; assign m_axi_awlen = '0;
    assign m_axi_awsize = '0; assign m_axi_awburst = '0; assign m_axi_awlock = 1'b0;
    assign m_axi_awcache = '0; assign m_axi_awprot = '0; assign m_axi_awregion = '0;
    assign m_axi_awqos = '0; assign m_axi_awvalid = 1'b0;
    assign m_axi_wdata = '0; assign m_axi_wstrb = '0; assign m_axi_wlast = 1'b0; assign m_axi_wvalid = 1'b0;
    assign m_axi_bready = 1'b0;
    assign m_axi_arid = '0; assign m_axi_araddr = '0; assign m_axi_arlen = '0;
    assign m_axi_arsize = '0; assign m_axi_arburst = '0; assign m_axi_arlock = 1'b0;
    assign m_axi_arcache = '0; assign m_axi_arprot = '0; assign m_axi_arregion = '0;
    assign m_axi_arqos = '0; assign m_axi_arvalid = 1'b0;
    assign m_axi_rready = 1'b0;
endmodule

`endif
